fix(bookmark-module): fixing the infinite loading
equinor/fusion-framework pull request #1693
Opened 2024-01-16 07:48 UTC by Noggling

fixing the infinite loading if a bookmark is created in classic fusion.

## Why

closes:

### Check off the following:
- [x] Confirm that I checked changes to branch which I am merging into.
  - _I have validated included files_
  - _My code does not generate new linting warnings_
  - _My PR is not a duplicate, [check existing pr`s](https://github.com/equinor/fusion-framework/pulls)_
- [x] Confirm that the I have completed the [self-review checklist](https://github.com/equinor/fusion-framework/blob/main/contributing/self-review.md).

- [x] Confirm that my changes meet our [code of conduct](https://github.com/equinor/fusion-framework/blob/main/CODE_OF_CONDUCT.md).

#### Conditional
- [ ] Confirm project selected and category, actual, iteration are set
- [ ] Confirm Milestone selected _(if any)_

2024-01-16 09:42 UTC, asbjornhaland approved these changes

2024-01-16 09:45 UTC, asbjornhaland requested changes
`sourceSystem` should be nullable for backward capabilities.

2024-01-17 08:38 UTC, Noggling commented
Dette haster @asbjornhaland og @odinr  feiler i prod hos oss :/

2024-01-17 08:45 UTC, odinr approved these changes

2024-01-17 08:47 UTC, odinr commented
@Noggling need to resolve @asbjornhaland conversation

2024-01-17 08:48 UTC, asbjornhaland approved these changes

2024-01-17 08:48 UTC, merged