Feat/fusion framework/person components cookbook
equinor/fusion-framework pull request #961
Opened 2023-06-15 08:58 UTC by AndrejNikolicEq

## Why

- Working example of PersonCard and PersonAvatar
- Profile image from Person resolver

closes:

### Check off the following:
- [x] Confirm that I checked changes to branch which I am merging into.
  - _I have validated included files_
  - _My code does not generate new linting warnings_
  - _My PR is not a duplicate, [check existing pr`s](https://github.com/equinor/fusion-framework/pulls)_
- [x] Confirm that the I have completed the [self-review checklist](https://github.com/equinor/fusion-framework/blob/main/contributing/self-review.md).

- [x] Confirm that my changes meet our [code of conduct](https://github.com/equinor/fusion-framework/blob/main/CODE_OF_CONDUCT.md).

#### Conditional
- [ ] Confirm project selected and category, actual, iteration are set
- [ ] Confirm Milestone selected _(if any)_

2023-06-16 06:40 UTC, odinr requested changes
Fix comments and add change set

2023-06-16 06:40 UTC, odinr commented on cookbooks/app-react-person-component/src/App.tsx
> +        <StrictMode>
Remove

2023-06-16 06:40 UTC, odinr commented on cookbooks/app-react-person-component/src/App.tsx
> +);
Change to StyledComponents and import EDS token

2023-06-16 06:40 UTC, odinr commented on cookbooks/app-react-person-component/CHANGELOG.md
Clear content

2023-08-16 12:02 UTC, AndrejNikolicEq commented
done in #1107

2023-08-16 12:02 UTC, closed without merging